@startuml
autonumber

participant "App" as app

participant "WRTC\nAPI" as wrtcAPI

participant "Connector\nHyperty" as voiceH

participant "Connection\nController" as connCtrl

participant "Connection\nData Object" as Conn

participant "Message Factory" as msgF

participant "Syncher" as sync

participant "Message BUS" as bus

app ->  voiceH : addListener( callback )

note over voiceH
  App listener to receive incoming connection requests
end note

newpage

app ->  voiceH : connect( bobHypertyURL, options )

group Connection Invite Bob

voiceH -> wrtcAPI : get CommResources\n(incl SDP)

voiceH <-- wrtcAPI : return CommResources\n(incl SDP)

voiceH -> sync : create\n( connectionObjSchema, CommResources, bobHypertyURL )

create Conn

sync -> Conn : new()

sync -> sync : Object.observe( Connection )

sync -> bus : postMessage( createConnectionObjectReqMsg )

...

sync <- bus : postMessage( createConnectionObjectResOkMsg )

voiceH <-- sync : return ConnectionDataObject

end group

create connCtrl

voiceH -> connCtrl : new( ConnectionDataObject )

app <-- voiceH :  return ConnectionController

@enduml
